name: Bazel

on:
  pull_request: {}
  push: {}

jobs:
  build_on_latest_ubuntu:
    name: Linux Ubuntu (latest) build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - name: Install OpenGL
      run: sudo apt-get install -y libgl1-mesa-dev

    - name: Install Qt6
      run: sudo apt-get install qt6-base-dev qt6-declarative-dev qt6-quick3d-dev

    - name: Mount bazel cache
      uses: actions/cache@v3.2.6
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Query Qt6 Bazel targets
      run: cd examples && bazelisk query '@qt//...'
     
    - name: Build
      run: |
        cd examples
        bazelisk build //...

